from dataclasses import dataclass, field


@dataclass(frozen=True)
class ExerciseTaxonomySeed:
    canonical_exercise_name: str
    family_slug: str
    base_movement_slug: str
    visual_identity_slug: str
    taxonomy_status: str
    variants: dict[str, str] = field(default_factory=dict)
    variant_extensions: dict[str, str] = field(default_factory=dict)


EXERCISE_TAXONOMY_SEEDS = (
    ExerciseTaxonomySeed(
        "Push-Up", "horizontal_press", "push_up", "visual_push_up", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Incline Push-Up",
        "horizontal_press",
        "push_up",
        "visual_incline_push_up",
        "reviewed",
        {"support_type": "bench", "bench_angle": "incline"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bodyweight Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_bodyweight_squat",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Reverse Lunge",
        "unilateral_knee_dominant",
        "reverse_lunge",
        "visual_reverse_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Split Squat",
        "unilateral_knee_dominant",
        "split_squat",
        "visual_split_squat",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Glute Bridge",
        "hip_extension",
        "glute_bridge",
        "visual_glute_bridge",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Plank", "core_anti_extension", "plank", "visual_plank", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Side Plank",
        "lateral_core_stability",
        "side_plank",
        "visual_side_plank",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dead Bug",
        "core_anti_extension",
        "dead_bug",
        "visual_dead_bug",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Mountain Climber",
        "ground_conditioning",
        "mountain_climber",
        "visual_mountain_climber",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Inverted Row", "rowing", "row", "visual_inverted_row", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Bench Press",
        "horizontal_press",
        "bench_press",
        "visual_dumbbell_bench_press",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Incline Dumbbell Press",
        "horizontal_press",
        "bench_press",
        "visual_incline_dumbbell_press",
        "reviewed",
        {"support_type": "bench", "bench_angle": "incline"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Shoulder Press",
        "vertical_press",
        "overhead_press",
        "visual_dumbbell_shoulder_press",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "One-Arm Dumbbell Row",
        "rowing",
        "row",
        "visual_one_arm_dumbbell_row",
        "reviewed",
        {"support_type": "bench", "laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Row",
        "rowing",
        "dumbbell_row",
        "visual_dumbbell_row",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Chest-Supported Dumbbell Row",
        "rowing",
        "row",
        "visual_chest_supported_dumbbell_row",
        "reviewed",
        {"support_type": "bench", "body_position": "chest_supported"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Chest-Supported Row",
        "rowing",
        "row",
        "visual_chest_supported_row",
        "alias_candidate",
        {"support_type": "bench", "body_position": "chest_supported"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell RDL",
        "hip_hinge",
        "romanian_deadlift",
        "visual_dumbbell_rdl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Goblet Squat",
        "bilateral_knee_dominant",
        "goblet_squat",
        "visual_goblet_squat",
        "reviewed",
        {"load_position": "goblet"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Split Squat",
        "unilateral_knee_dominant",
        "split_squat",
        "visual_dumbbell_split_squat",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Reverse Lunge",
        "unilateral_knee_dominant",
        "reverse_lunge",
        "visual_dumbbell_reverse_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Lateral Raise",
        "shoulder_elevation",
        "lateral_raise",
        "visual_dumbbell_lateral_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Curl",
        "elbow_flexion",
        "curl",
        "visual_dumbbell_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Triceps Extension",
        "elbow_extension",
        "triceps_extension",
        "visual_dumbbell_triceps_extension",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Farmer Carry",
        "loaded_carry",
        "farmer_carry",
        "visual_farmer_carry",
        "reviewed",
        {
            "laterality": "bilateral",
            "load_position": "sides",
            "locomotion_mode": "walk",
        },
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Squat",
        "bilateral_knee_dominant",
        "barbell_squat_unspecified",
        "visual_barbell_squat",
        "review_required",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Back Squat",
        "bilateral_knee_dominant",
        "back_squat",
        "visual_back_squat",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Front Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_front_squat",
        "reviewed",
        {"load_position": "front_rack"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Bench Press",
        "horizontal_press",
        "bench_press",
        "visual_barbell_bench_press",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Overhead Press",
        "vertical_press",
        "overhead_press",
        "visual_overhead_press",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Row", "rowing", "barbell_row", "visual_barbell_row", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Romanian Deadlift",
        "hip_hinge",
        "romanian_deadlift",
        "visual_romanian_deadlift",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Conventional Deadlift",
        "hip_hinge",
        "conventional_deadlift",
        "visual_conventional_deadlift",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Hip Thrust",
        "hip_extension",
        "hip_thrust",
        "visual_hip_thrust",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Curl", "elbow_flexion", "curl", "visual_ez_bar_curl", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Skull Crusher",
        "elbow_extension",
        "skull_crusher",
        "visual_ez_bar_skull_crusher",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Close-Grip Press",
        "horizontal_press",
        "bench_press",
        "visual_ez_bar_close_grip_press",
        "reviewed",
        {"support_type": "bench", "grip": "close"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Pull-Up",
        "vertical_pull",
        "pull_up",
        "visual_pull_up",
        "reviewed",
        {"grip": "pronated"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Chin-Up",
        "vertical_pull",
        "chin_up",
        "visual_chin_up",
        "reviewed",
        {"grip": "supinated"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band-Assisted Pull-Up",
        "vertical_pull",
        "pull_up",
        "visual_band_assisted_pull_up",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Hanging Knee Raise",
        "trunk_flexion",
        "hanging_knee_raise",
        "visual_hanging_knee_raise",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Pull-Apart",
        "rear_delt_retraction",
        "band_pull_apart",
        "visual_band_pull_apart",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Face Pull",
        "rear_delt_retraction",
        "face_pull",
        "visual_band_face_pull",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Row", "rowing", "row", "visual_band_row", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Band Triceps Pressdown",
        "elbow_extension",
        "triceps_pressdown",
        "visual_band_triceps_pressdown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band External Rotation",
        "shoulder_rotation",
        "external_rotation",
        "visual_band_external_rotation",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Row",
        "rowing",
        "cable_row",
        "visual_cable_row",
        "reviewed",
        {"movement_direction": "horizontal"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Lat Pulldown",
        "vertical_pull",
        "lat_pulldown",
        "visual_cable_lat_pulldown",
        "alias_candidate",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Lat Pulldown",
        "vertical_pull",
        "lat_pulldown",
        "visual_lat_pulldown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Face Pull",
        "rear_delt_retraction",
        "face_pull",
        "visual_cable_face_pull",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Triceps Pressdown",
        "elbow_extension",
        "triceps_pressdown",
        "visual_cable_triceps_pressdown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Curl", "elbow_flexion", "curl", "visual_cable_curl", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Cable Lateral Raise",
        "shoulder_elevation",
        "lateral_raise",
        "visual_cable_lateral_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Woodchop",
        "rotational_core",
        "woodchop",
        "visual_cable_woodchop",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Leg Press",
        "bilateral_knee_dominant",
        "leg_press",
        "visual_leg_press",
        "reviewed",
        {"support_type": "machine"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Machine Chest Press",
        "horizontal_press",
        "machine_chest_press",
        "visual_machine_chest_press",
        "reviewed",
        {"support_type": "machine"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Machine Row", "rowing", "row", "visual_machine_row", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Treadmill Walk",
        "treadmill_locomotion",
        "treadmill_walk",
        "visual_treadmill_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Incline Walk",
        "treadmill_locomotion",
        "treadmill_walk",
        "visual_treadmill_incline_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {"grade": "incline"},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Intervals",
        "treadmill_locomotion",
        "treadmill_locomotion_unspecified",
        "visual_treadmill_intervals",
        "reviewed",
        {"locomotion_mode": "unspecified"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Steady State",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Intervals",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bear Crawl",
        "quadrupedal_locomotion",
        "bear_crawl",
        "visual_bear_crawl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bird Dog",
        "core_anti_rotation",
        "bird_dog",
        "visual_bird_dog",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Hollow Body Hold",
        "core_anti_extension",
        "hollow_hold",
        "visual_hollow_body_hold",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Hollow Rock",
        "trunk_flexion",
        "hollow_rock",
        "visual_hollow_rock",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Superman Hold",
        "back_extension",
        "superman_hold",
        "visual_superman_hold",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Walking Lunge",
        "unilateral_knee_dominant",
        "walking_lunge",
        "visual_walking_lunge",
        "reviewed",
        {"stance": "split", "locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Lateral Lunge",
        "unilateral_knee_dominant",
        "lateral_lunge",
        "visual_lateral_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Wall Sit",
        "bilateral_knee_dominant",
        "wall_sit",
        "visual_wall_sit",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Standing Calf Raise",
        "ankle_plantarflexion",
        "calf_raise",
        "visual_standing_calf_raise",
        "review_required",
        {"body_position": "standing"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Single-Leg Glute Bridge",
        "hip_extension",
        "glute_bridge",
        "visual_single_leg_glute_bridge",
        "reviewed",
        {"laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Pike Push-Up",
        "vertical_press",
        "pike_push_up",
        "visual_pike_push_up",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Close-Grip Push-Up",
        "horizontal_press",
        "push_up",
        "visual_close_grip_push_up",
        "reviewed",
        {"grip": "close"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Tempo Push-Up",
        "horizontal_press",
        "push_up",
        "visual_push_up",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Decline Push-Up",
        "horizontal_press",
        "push_up",
        "visual_decline_push_up",
        "reviewed",
        {"support_type": "bench", "bench_angle": "decline"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bench Dip",
        "elbow_extension",
        "dip",
        "visual_bench_dip",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Floor Press",
        "horizontal_press",
        "bench_press",
        "visual_dumbbell_floor_press",
        "reviewed",
        {"support_type": "floor"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Fly",
        "chest_fly",
        "chest_fly",
        "visual_dumbbell_fly",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Incline Dumbbell Fly",
        "chest_fly",
        "chest_fly",
        "visual_incline_dumbbell_fly",
        "reviewed",
        {"support_type": "bench", "bench_angle": "incline"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Pullover",
        "shoulder_extension",
        "dumbbell_pullover",
        "visual_dumbbell_pullover",
        "reviewed",
        {"support_type": "bench", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Arnold Press",
        "vertical_press",
        "arnold_press",
        "visual_arnold_press",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Seated Dumbbell Shoulder Press",
        "vertical_press",
        "overhead_press",
        "visual_seated_dumbbell_shoulder_press",
        "reviewed",
        {"support_type": "bench", "body_position": "seated"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Front Raise",
        "shoulder_elevation",
        "front_raise",
        "visual_dumbbell_front_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Rear Delt Fly",
        "rear_delt_retraction",
        "rear_delt_fly",
        "visual_dumbbell_rear_delt_fly",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Chest-Supported Rear Delt Fly",
        "rear_delt_retraction",
        "rear_delt_fly",
        "visual_chest_supported_rear_delt_fly",
        "reviewed",
        {"support_type": "bench", "body_position": "chest_supported"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Shrug",
        "scapular_elevation",
        "shrug",
        "visual_dumbbell_shrug",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Upright Row",
        "shoulder_elevation",
        "upright_row",
        "visual_dumbbell_upright_row",
        "reviewed",
        {"movement_direction": "vertical"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Hammer Curl",
        "elbow_flexion",
        "hammer_curl",
        "visual_dumbbell_hammer_curl",
        "reviewed",
        {"grip": "hammer"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Concentration Curl",
        "elbow_flexion",
        "concentration_curl",
        "visual_dumbbell_concentration_curl",
        "reviewed",
        {"support_type": "thigh"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Zottman Curl",
        "elbow_flexion",
        "zottman_curl",
        "visual_dumbbell_zottman_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Kickback",
        "elbow_extension",
        "triceps_kickback",
        "visual_dumbbell_kickback",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Skull Crusher",
        "elbow_extension",
        "skull_crusher",
        "visual_dumbbell_skull_crusher",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Close-Grip Press",
        "horizontal_press",
        "bench_press",
        "visual_dumbbell_close_grip_press",
        "reviewed",
        {"support_type": "bench", "grip": "close"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Step-Up",
        "unilateral_knee_dominant",
        "step_up",
        "visual_dumbbell_step_up",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Lateral Lunge",
        "unilateral_knee_dominant",
        "lateral_lunge",
        "visual_dumbbell_lateral_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Bulgarian Split Squat",
        "unilateral_knee_dominant",
        "split_squat",
        "visual_dumbbell_bulgarian_split_squat",
        "reviewed",
        {"support_type": "bench", "stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Sumo Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_dumbbell_sumo_squat",
        "reviewed",
        {"stance": "sumo"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Front Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_dumbbell_front_squat",
        "reviewed",
        {"load_position": "front_rack"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Single-Leg RDL",
        "hip_hinge",
        "romanian_deadlift",
        "visual_dumbbell_single_leg_rdl",
        "reviewed",
        {"laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Hip Thrust",
        "hip_extension",
        "hip_thrust",
        "visual_dumbbell_hip_thrust",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Suitcase Carry",
        "loaded_carry",
        "suitcase_carry",
        "visual_suitcase_carry",
        "reviewed",
        {
            "laterality": "unilateral",
            "load_position": "suitcase",
            "locomotion_mode": "walk",
        },
        {},
    ),
    ExerciseTaxonomySeed(
        "Waiter Carry",
        "loaded_carry",
        "waiter_carry",
        "visual_waiter_carry",
        "reviewed",
        {
            "laterality": "unilateral",
            "load_position": "overhead",
            "locomotion_mode": "walk",
        },
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Front Rack Carry",
        "loaded_carry",
        "front_rack_carry",
        "visual_dumbbell_front_rack_carry",
        "reviewed",
        {"load_position": "front_rack", "locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Calf Raise",
        "ankle_plantarflexion",
        "calf_raise",
        "visual_dumbbell_calf_raise",
        "review_required",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Pause Squat",
        "bilateral_knee_dominant",
        "barbell_squat_unspecified",
        "visual_pause_squat",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Box Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_box_squat",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Reverse Lunge",
        "unilateral_knee_dominant",
        "reverse_lunge",
        "visual_barbell_reverse_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Split Squat",
        "unilateral_knee_dominant",
        "split_squat",
        "visual_barbell_split_squat",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Good Morning",
        "hip_hinge",
        "good_morning",
        "visual_barbell_good_morning",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Glute Bridge",
        "hip_extension",
        "glute_bridge",
        "visual_barbell_glute_bridge",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Floor Press",
        "horizontal_press",
        "bench_press",
        "visual_barbell_floor_press",
        "reviewed",
        {"support_type": "floor"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Close-Grip Bench Press",
        "horizontal_press",
        "bench_press",
        "visual_close_grip_bench_press",
        "reviewed",
        {"support_type": "bench", "grip": "close"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Incline Barbell Bench Press",
        "horizontal_press",
        "bench_press",
        "visual_incline_barbell_bench_press",
        "reviewed",
        {"support_type": "bench", "bench_angle": "incline"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Push Press",
        "vertical_press",
        "push_press",
        "visual_push_press",
        "reviewed",
        {"execution_mode": "dynamic"},
        {"lower_body_drive": "deliberate"},
    ),
    ExerciseTaxonomySeed(
        "Pendlay Row", "rowing", "pendlay_row", "visual_pendlay_row", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Barbell High Pull",
        "vertical_power_pull",
        "high_pull",
        "visual_barbell_high_pull",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Curl",
        "elbow_flexion",
        "curl",
        "visual_barbell_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Rollout",
        "core_anti_extension",
        "rollout",
        "visual_barbell_rollout",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Plate Front Raise",
        "shoulder_elevation",
        "shoulder_raise",
        "visual_plate_front_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Plate Curl", "elbow_flexion", "curl", "visual_plate_curl", "reviewed", {}, {}
    ),
    ExerciseTaxonomySeed(
        "Plate Pinch Carry",
        "loaded_carry",
        "pinch_grip_carry",
        "visual_plate_pinch_carry",
        "reviewed",
        {"grip": "pinch", "locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Reverse Curl",
        "elbow_flexion",
        "reverse_curl",
        "visual_ez_bar_reverse_curl",
        "reviewed",
        {"grip": "reverse"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Preacher-Style Curl",
        "elbow_flexion",
        "preacher_curl",
        "visual_ez_bar_preacher_style_curl",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Overhead Triceps Extension",
        "elbow_extension",
        "overhead_triceps_extension",
        "visual_ez_bar_overhead_triceps_extension",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Upright Row",
        "shoulder_elevation",
        "upright_row",
        "visual_ez_bar_upright_row",
        "reviewed",
        {"movement_direction": "vertical"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Neutral-Grip Pull-Up",
        "vertical_pull",
        "pull_up",
        "visual_neutral_grip_pull_up",
        "reviewed",
        {"grip": "neutral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Negative Pull-Up",
        "vertical_pull",
        "pull_up",
        "visual_negative_pull_up",
        "reviewed",
        {"execution_mode": "eccentric_only"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Scapular Pull-Up",
        "vertical_pull",
        "pull_up",
        "visual_scapular_pull_up",
        "reviewed",
        {},
        {"range_of_motion_variant": "scapular"},
    ),
    ExerciseTaxonomySeed(
        "Commando Pull-Up",
        "vertical_pull",
        "commando_pull_up",
        "visual_commando_pull_up",
        "reviewed",
        {"grip": "mixed"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dead Hang",
        "vertical_pull",
        "bar_hang",
        "visual_dead_hang",
        "alias_candidate",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Hanging Leg Raise",
        "trunk_flexion",
        "hanging_leg_raise",
        "visual_hanging_leg_raise",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Hanging Oblique Knee Raise",
        "lateral_trunk_flexion",
        "hanging_oblique_knee_raise",
        "visual_hanging_oblique_knee_raise",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Biceps Curl",
        "elbow_flexion",
        "curl",
        "visual_band_biceps_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Hammer Curl",
        "elbow_flexion",
        "hammer_curl",
        "visual_band_hammer_curl",
        "reviewed",
        {"grip": "hammer"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Overhead Triceps Extension",
        "elbow_extension",
        "overhead_triceps_extension",
        "visual_band_overhead_triceps_extension",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Lateral Raise",
        "shoulder_elevation",
        "shoulder_raise",
        "visual_band_lateral_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Shoulder Press",
        "vertical_press",
        "overhead_press",
        "visual_band_shoulder_press",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Lat Pulldown",
        "vertical_pull",
        "lat_pulldown",
        "visual_band_lat_pulldown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Straight-Arm Pulldown",
        "vertical_pull",
        "straight_arm_pulldown",
        "visual_band_straight_arm_pulldown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Pull-Through",
        "hip_hinge",
        "pull_through",
        "visual_band_pull_through",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Good Morning",
        "hip_hinge",
        "good_morning",
        "visual_band_good_morning",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Resisted Push-Up",
        "horizontal_press",
        "push_up",
        "visual_band_resisted_push_up",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Pallof Press",
        "core_anti_rotation",
        "pallof_press",
        "visual_band_pallof_press",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Woodchop",
        "rotational_core",
        "woodchop",
        "visual_band_woodchop",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Lateral Walk",
        "hip_abduction",
        "lateral_walk",
        "visual_band_lateral_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Monster Walk",
        "hip_abduction",
        "monster_walk",
        "visual_band_monster_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Glute Bridge",
        "hip_extension",
        "glute_bridge",
        "visual_band_glute_bridge",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Single-Arm Cable Row",
        "rowing",
        "row",
        "visual_single_arm_cable_row",
        "reviewed",
        {"laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable High Row",
        "rowing",
        "high_row",
        "visual_cable_high_row",
        "reviewed",
        {"movement_direction": "high_diagonal"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Reverse Fly",
        "rear_delt_retraction",
        "rear_delt_fly",
        "visual_cable_reverse_fly",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Chest Fly",
        "chest_fly",
        "chest_fly",
        "visual_cable_chest_fly",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Single-Arm Cable Press",
        "horizontal_press",
        "standing_chest_press",
        "visual_single_arm_cable_press",
        "reviewed",
        {"laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Upright Row",
        "shoulder_elevation",
        "upright_row",
        "visual_cable_upright_row",
        "reviewed",
        {"movement_direction": "vertical"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Y Raise",
        "shoulder_elevation",
        "y_raise",
        "visual_cable_y_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable External Rotation",
        "shoulder_rotation",
        "external_rotation",
        "visual_cable_external_rotation",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Internal Rotation",
        "shoulder_rotation",
        "internal_rotation",
        "visual_cable_internal_rotation",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Pull-Through",
        "hip_hinge",
        "pull_through",
        "visual_cable_pull_through",
        "reviewed",
        {"attachment": "rope"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Crunch",
        "trunk_flexion",
        "cable_crunch",
        "visual_cable_crunch",
        "reviewed",
        {"attachment": "rope", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Pallof Press",
        "core_anti_rotation",
        "pallof_press",
        "visual_cable_pallof_press",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Rope Triceps Pressdown",
        "elbow_extension",
        "triceps_pressdown",
        "visual_rope_triceps_pressdown",
        "reviewed",
        {"attachment": "rope"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Rope Overhead Triceps Extension",
        "elbow_extension",
        "overhead_triceps_extension",
        "visual_rope_overhead_triceps_extension",
        "reviewed",
        {"attachment": "rope"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Rope Hammer Curl",
        "elbow_flexion",
        "hammer_curl",
        "visual_rope_hammer_curl",
        "reviewed",
        {"grip": "hammer", "attachment": "rope"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Rope Face Pull",
        "rear_delt_retraction",
        "face_pull",
        "visual_rope_face_pull",
        "reviewed",
        {"attachment": "rope"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Straight-Arm Cable Pulldown",
        "vertical_pull",
        "straight_arm_pulldown",
        "visual_straight_arm_cable_pulldown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Stability Ball Hamstring Curl",
        "knee_flexion",
        "hamstring_curl",
        "visual_stability_ball_hamstring_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Stability Ball Rollout",
        "core_anti_extension",
        "rollout",
        "visual_stability_ball_rollout",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Stability Ball Plank",
        "core_anti_extension",
        "plank",
        "visual_stability_ball_plank",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Stability Ball Stir-the-Pot",
        "core_anti_extension",
        "stir_the_pot",
        "visual_stability_ball_stir_the_pot",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Stability Ball Wall Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_stability_ball_wall_squat",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Stability Ball Dead Bug",
        "core_anti_extension",
        "dead_bug",
        "visual_stability_ball_dead_bug",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Easy Jog",
        "treadmill_locomotion",
        "treadmill_jog",
        "visual_treadmill_easy_jog",
        "reviewed",
        {"locomotion_mode": "jog"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Hill Intervals",
        "treadmill_locomotion",
        "treadmill_locomotion_unspecified",
        "visual_treadmill_hill_intervals",
        "reviewed",
        {"locomotion_mode": "unspecified"},
        {"grade": "incline"},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Tempo Run",
        "treadmill_locomotion",
        "treadmill_run",
        "visual_treadmill_tempo_run",
        "reviewed",
        {"locomotion_mode": "run"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Recovery Ride",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Tempo Ride",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Hill Intervals",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Wall Push-Up",
        "horizontal_press",
        "push_up",
        "visual_wall_push_up",
        "reviewed",
        {"body_position": "standing", "support_type": "wall"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Scapular Push-Up",
        "horizontal_press",
        "push_up",
        "visual_scapular_push_up",
        "reviewed",
        {},
        {"range_of_motion_variant": "scapular"},
    ),
    ExerciseTaxonomySeed(
        "Plank Shoulder Tap",
        "core_anti_rotation",
        "plank_shoulder_tap",
        "visual_plank_shoulder_tap",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Reverse Crunch",
        "trunk_flexion",
        "reverse_crunch",
        "visual_reverse_crunch",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Heel Tap",
        "trunk_flexion",
        "heel_tap",
        "visual_heel_tap",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Side Plank Reach-Through",
        "lateral_core_stability",
        "side_plank",
        "visual_side_plank_reach_through",
        "reviewed",
        {"execution_mode": "dynamic", "movement_direction": "rotation"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Seated Knee Tuck",
        "trunk_flexion",
        "seated_knee_tuck",
        "visual_seated_knee_tuck",
        "reviewed",
        {"body_position": "seated", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Toe Walk",
        "gait_drill",
        "toe_walk",
        "visual_toe_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Heel Walk",
        "gait_drill",
        "heel_walk",
        "visual_heel_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Prone Y-T-W Raise",
        "shoulder_mobility",
        "prone_y_t_w_raise",
        "visual_prone_y_t_w_raise",
        "reviewed",
        {"body_position": "prone", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cat-Cow",
        "mobility",
        "cat_cow",
        "visual_cat_cow",
        "reviewed",
        {"body_position": "quadruped", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Quadruped T-Spine Rotation",
        "mobility",
        "quadruped_t_spine_rotation",
        "visual_quadruped_t_spine_rotation",
        "reviewed",
        {"body_position": "quadruped", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Half-Kneeling Hip Flexor Stretch",
        "mobility",
        "hip_flexor_stretch",
        "visual_half_kneeling_hip_flexor_stretch",
        "reviewed",
        {"body_position": "half_kneeling", "execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "90/90 Hip Switch",
        "mobility",
        "hip_90_90_switch",
        "visual_90_90_hip_switch",
        "reviewed",
        {"body_position": "seated", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Child's Pose Lat Stretch",
        "mobility",
        "childs_pose_lat_stretch",
        "visual_childs_pose_lat_stretch",
        "reviewed",
        {"body_position": "childs_pose", "execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Wall Slide",
        "shoulder_mobility",
        "wall_slide",
        "visual_wall_slide",
        "reviewed",
        {"support_type": "wall", "execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Squeeze Press",
        "horizontal_press",
        "squeeze_press",
        "visual_dumbbell_squeeze_press",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Low-Incline Dumbbell Press",
        "horizontal_press",
        "bench_press",
        "visual_low_incline_dumbbell_press",
        "reviewed",
        {"support_type": "bench", "bench_angle": "low_incline"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Tate Press",
        "elbow_extension",
        "tate_press",
        "visual_dumbbell_tate_press",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Reverse Curl",
        "elbow_flexion",
        "reverse_curl",
        "visual_dumbbell_reverse_curl",
        "reviewed",
        {"grip": "reverse"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Cross-Body Hammer Curl",
        "elbow_flexion",
        "hammer_curl",
        "visual_dumbbell_cross_body_hammer_curl",
        "reviewed",
        {"grip": "hammer", "movement_direction": "cross_body"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Spider Curl",
        "elbow_flexion",
        "spider_curl",
        "visual_dumbbell_spider_curl",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Suitcase Deadlift",
        "hip_hinge",
        "deadlift",
        "visual_dumbbell_suitcase_deadlift",
        "reviewed",
        {"laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Farmer March",
        "loaded_carry",
        "farmer_carry",
        "visual_dumbbell_farmer_march",
        "reviewed",
        {
            "laterality": "bilateral",
            "load_position": "sides",
            "locomotion_mode": "march",
        },
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Suitcase March",
        "loaded_carry",
        "suitcase_carry",
        "visual_dumbbell_suitcase_march",
        "reviewed",
        {
            "laterality": "unilateral",
            "load_position": "suitcase",
            "locomotion_mode": "march",
        },
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Tempo Goblet Squat",
        "bilateral_knee_dominant",
        "goblet_squat",
        "visual_goblet_squat",
        "reviewed",
        {"load_position": "goblet"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Heel-Elevated Goblet Squat",
        "bilateral_knee_dominant",
        "goblet_squat",
        "visual_dumbbell_heel_elevated_goblet_squat",
        "reviewed",
        {"load_position": "goblet"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Offset Reverse Lunge",
        "unilateral_knee_dominant",
        "reverse_lunge",
        "visual_dumbbell_offset_reverse_lunge",
        "reviewed",
        {"laterality": "unilateral", "stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Skater Squat",
        "unilateral_knee_dominant",
        "skater_squat",
        "visual_dumbbell_skater_squat",
        "reviewed",
        {"laterality": "unilateral"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Dumbbell Renegade Row",
        "rowing",
        "renegade_row",
        "visual_dumbbell_renegade_row",
        "reviewed",
        {"body_position": "plank"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Shrug",
        "scapular_elevation",
        "shrug",
        "visual_barbell_shrug",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Calf Raise",
        "ankle_plantarflexion",
        "calf_raise",
        "visual_barbell_calf_raise",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Rack Pull",
        "hip_hinge",
        "rack_pull",
        "visual_rack_pull",
        "reviewed",
        {},
        {"range": "partial"},
    ),
    ExerciseTaxonomySeed(
        "Barbell Hip Hinge Drill",
        "hip_hinge",
        "hip_hinge_drill",
        "visual_barbell_hip_hinge_drill",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Tall-Kneeling Press",
        "vertical_press",
        "overhead_press",
        "visual_barbell_tall_kneeling_press",
        "reviewed",
        {"body_position": "tall_kneeling"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Lunge",
        "unilateral_knee_dominant",
        "lunge",
        "visual_barbell_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Barbell Reverse-Grip Row",
        "rowing",
        "row",
        "visual_barbell_reverse_grip_row",
        "reviewed",
        {"grip": "reverse"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Drag Curl",
        "elbow_flexion",
        "drag_curl",
        "visual_ez_bar_drag_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar Close-Grip Floor Press",
        "horizontal_press",
        "bench_press",
        "visual_ez_bar_close_grip_floor_press",
        "reviewed",
        {"support_type": "floor", "grip": "close"},
        {},
    ),
    ExerciseTaxonomySeed(
        "EZ-Bar JM Press",
        "elbow_extension",
        "jm_press",
        "visual_ez_bar_jm_press",
        "reviewed",
        {"support_type": "bench"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Pull-Up Bar Dead Hang",
        "vertical_pull",
        "bar_hang",
        "visual_pull_up_bar_dead_hang",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Pull-Up Flexed-Arm Hang",
        "vertical_pull",
        "flexed_arm_hang",
        "visual_pull_up_flexed_arm_hang",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Chest Press",
        "horizontal_press",
        "standing_chest_press",
        "visual_band_chest_press",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Squat",
        "bilateral_knee_dominant",
        "squat",
        "visual_band_squat",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Split Squat",
        "unilateral_knee_dominant",
        "split_squat",
        "visual_band_split_squat",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Romanian Deadlift",
        "hip_hinge",
        "romanian_deadlift",
        "visual_band_romanian_deadlift",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Hamstring Curl",
        "knee_flexion",
        "hamstring_curl",
        "visual_band_hamstring_curl",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Dead Bug Pulldown",
        "core_anti_extension",
        "band_dead_bug_pulldown",
        "visual_band_dead_bug_pulldown",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Anti-Rotation Hold",
        "core_anti_rotation",
        "anti_rotation_hold",
        "visual_band_anti_rotation_hold",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Band Shoulder Dislocate",
        "shoulder_mobility",
        "shoulder_dislocate",
        "visual_band_shoulder_dislocate",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Chest Press",
        "horizontal_press",
        "standing_chest_press",
        "visual_cable_chest_press",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Rear Delt Row",
        "rear_delt_retraction",
        "rear_delt_row",
        "visual_cable_rear_delt_row",
        "reviewed",
        {"movement_direction": "horizontal"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable 90/90 External Rotation",
        "shoulder_rotation",
        "shoulder_90_90_external_rotation",
        "visual_cable_90_90_external_rotation",
        "reviewed",
        {"execution_mode": "dynamic"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Lateral Lunge",
        "unilateral_knee_dominant",
        "lateral_lunge",
        "visual_cable_lateral_lunge",
        "reviewed",
        {"stance": "split"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Romanian Deadlift",
        "hip_hinge",
        "romanian_deadlift",
        "visual_cable_romanian_deadlift",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Kickback",
        "hip_extension",
        "glute_kickback",
        "visual_cable_kickback",
        "review_required",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Cable Anti-Rotation Hold",
        "core_anti_rotation",
        "anti_rotation_hold",
        "visual_cable_anti_rotation_hold",
        "reviewed",
        {"execution_mode": "isometric"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Rope Cable Curl",
        "elbow_flexion",
        "curl",
        "visual_rope_cable_curl",
        "reviewed",
        {"attachment": "rope"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Recovery Walk",
        "treadmill_locomotion",
        "treadmill_walk",
        "visual_treadmill_walk",
        "reviewed",
        {"locomotion_mode": "walk"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Treadmill Easy Intervals",
        "treadmill_locomotion",
        "treadmill_locomotion_unspecified",
        "visual_treadmill_easy_intervals",
        "reviewed",
        {"locomotion_mode": "unspecified"},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Easy Spin",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
    ExerciseTaxonomySeed(
        "Bike Cadence Drill",
        "stationary_cycling",
        "stationary_bike",
        "visual_stationary_bike",
        "reviewed",
        {},
        {},
    ),
)
