"""Canonical exercise prescription measurement seed projection.

This runtime-owned manifest mirrors the Architecture-accepted v1 audit.
It is intentionally explicit and does not read project-memory artifacts.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExercisePrescriptionMeasurementSeed:
    canonical_exercise_name: str
    default_measurement_type: str
    allowed_measurement_types: tuple[str, ...]
    sets_applicable: bool
    load_applicability: str
    rir_applicability: str
    distance_unit: str | None


EXERCISE_PRESCRIPTION_MEASUREMENT_SEEDS: tuple[
    ExercisePrescriptionMeasurementSeed, ...
] = (
    ExercisePrescriptionMeasurementSeed(
        "Push-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Incline Push-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bodyweight Squat",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Reverse Lunge",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Split Squat",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Glute Bridge",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Plank",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Side Plank",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dead Bug",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Mountain Climber",
        "duration",
        ("reps", "duration"),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Inverted Row",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Bench Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Incline Dumbbell Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Shoulder Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "One-Arm Dumbbell Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Chest-Supported Dumbbell Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Chest-Supported Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell RDL",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Goblet Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Split Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Reverse Lunge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Lateral Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Triceps Extension",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Farmer Carry",
        "distance",
        ("duration", "distance"),
        True,
        "applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Back Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Front Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Bench Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Overhead Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Romanian Deadlift",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Conventional Deadlift",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Hip Thrust",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Skull Crusher",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Close-Grip Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Pull-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Chin-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band-Assisted Pull-Up",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Hanging Knee Raise",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Pull-Apart",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Face Pull",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Triceps Pressdown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band External Rotation",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Lat Pulldown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Lat Pulldown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Face Pull",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Triceps Pressdown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Lateral Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Woodchop",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Leg Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Machine Chest Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Machine Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Walk",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Incline Walk",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Intervals",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Steady State",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Intervals",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bear Crawl",
        "distance",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bird Dog",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Hollow Body Hold",
        "duration",
        ("duration",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Hollow Rock",
        "reps",
        ("reps", "duration"),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Superman Hold",
        "duration",
        ("duration",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Walking Lunge",
        "reps",
        ("reps", "distance"),
        True,
        "optional",
        "ambiguous",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Lateral Lunge",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Wall Sit",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Standing Calf Raise",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Single-Leg Glute Bridge",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Pike Push-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Close-Grip Push-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Tempo Push-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Decline Push-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bench Dip",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Floor Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Fly",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Incline Dumbbell Fly",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Pullover",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Arnold Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Seated Dumbbell Shoulder Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Front Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Rear Delt Fly",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Chest-Supported Rear Delt Fly",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Shrug",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Upright Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Hammer Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Concentration Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Zottman Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Kickback",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Skull Crusher",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Close-Grip Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Step-Up",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Lateral Lunge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Bulgarian Split Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Sumo Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Front Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Single-Leg RDL",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Hip Thrust",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Suitcase Carry",
        "distance",
        ("duration", "distance"),
        True,
        "applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Waiter Carry",
        "distance",
        ("duration", "distance"),
        True,
        "applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Front Rack Carry",
        "distance",
        ("duration", "distance"),
        True,
        "applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Calf Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Pause Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Box Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Reverse Lunge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Split Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Good Morning",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Glute Bridge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Floor Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Close-Grip Bench Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Incline Barbell Bench Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Push Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Pendlay Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell High Pull",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Rollout",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Plate Front Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Plate Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Plate Pinch Carry",
        "distance",
        ("duration", "distance"),
        True,
        "applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Reverse Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Preacher-Style Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Overhead Triceps Extension",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Upright Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Neutral-Grip Pull-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Negative Pull-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Scapular Pull-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Commando Pull-Up",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dead Hang",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Hanging Leg Raise",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Hanging Oblique Knee Raise",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Biceps Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Hammer Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Overhead Triceps Extension",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Lateral Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Shoulder Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Lat Pulldown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Straight-Arm Pulldown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Pull-Through",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Good Morning",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Resisted Push-Up",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Pallof Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Woodchop",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Lateral Walk",
        "reps",
        ("reps", "distance"),
        True,
        "applicable",
        "ambiguous",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Monster Walk",
        "reps",
        ("reps", "distance"),
        True,
        "applicable",
        "ambiguous",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Glute Bridge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Single-Arm Cable Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable High Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Reverse Fly",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Chest Fly",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Single-Arm Cable Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Upright Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Y Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable External Rotation",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Internal Rotation",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Pull-Through",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Crunch",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Pallof Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Rope Triceps Pressdown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Rope Overhead Triceps Extension",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Rope Hammer Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Rope Face Pull",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Straight-Arm Cable Pulldown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Stability Ball Hamstring Curl",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Stability Ball Rollout",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Stability Ball Plank",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Stability Ball Stir-the-Pot",
        "reps",
        ("reps", "duration"),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Stability Ball Wall Squat",
        "reps",
        ("reps",),
        True,
        "optional",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Stability Ball Dead Bug",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Easy Jog",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Hill Intervals",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Tempo Run",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Recovery Ride",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Tempo Ride",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Hill Intervals",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Wall Push-Up",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Scapular Push-Up",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Plank Shoulder Tap",
        "reps",
        ("reps", "duration"),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Reverse Crunch",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Heel Tap",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Side Plank Reach-Through",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Seated Knee Tuck",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Toe Walk",
        "distance",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Heel Walk",
        "distance",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Prone Y-T-W Raise",
        "reps",
        ("reps",),
        True,
        "optional",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cat-Cow",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Quadruped T-Spine Rotation",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Half-Kneeling Hip Flexor Stretch",
        "duration",
        ("duration",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "90/90 Hip Switch",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Child's Pose Lat Stretch",
        "duration",
        ("duration",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Wall Slide",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Squeeze Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Low-Incline Dumbbell Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Tate Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Reverse Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Cross-Body Hammer Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Spider Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Suitcase Deadlift",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Farmer March",
        "reps",
        ("reps", "duration"),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Suitcase March",
        "reps",
        ("reps", "duration"),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Tempo Goblet Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Heel-Elevated Goblet Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Offset Reverse Lunge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Skater Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Dumbbell Renegade Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Shrug",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Calf Raise",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Rack Pull",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Hip Hinge Drill",
        "reps",
        ("reps",),
        True,
        "applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Tall-Kneeling Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Lunge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Barbell Reverse-Grip Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Drag Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar Close-Grip Floor Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "EZ-Bar JM Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Pull-Up Bar Dead Hang",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Pull-Up Flexed-Arm Hang",
        "duration",
        ("duration",),
        True,
        "optional",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Chest Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Split Squat",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Romanian Deadlift",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Hamstring Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Dead Bug Pulldown",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Anti-Rotation Hold",
        "duration",
        ("duration",),
        True,
        "applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Band Shoulder Dislocate",
        "reps",
        ("reps",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Chest Press",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Rear Delt Row",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable 90/90 External Rotation",
        "reps",
        ("reps",),
        True,
        "applicable",
        "ambiguous",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Lateral Lunge",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Romanian Deadlift",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Kickback",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Cable Anti-Rotation Hold",
        "duration",
        ("duration",),
        True,
        "applicable",
        "not_applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Rope Cable Curl",
        "reps",
        ("reps",),
        True,
        "applicable",
        "applicable",
        None,
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Recovery Walk",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Treadmill Easy Intervals",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Easy Spin",
        "duration",
        ("duration", "distance"),
        True,
        "not_applicable",
        "not_applicable",
        "meters",
    ),
    ExercisePrescriptionMeasurementSeed(
        "Bike Cadence Drill",
        "duration",
        ("duration",),
        True,
        "not_applicable",
        "not_applicable",
        None,
    ),
)
