from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StarterFoodDefinition:
    display_name: str
    aliases: tuple[str, ...]
    search_terms: tuple[str, ...]
    prefer_terms: tuple[str, ...]
    avoid_terms: tuple[str, ...]
    category: str
    notes: str
    raw_source_safe: bool = True


STARTER_FOOD_DEFINITIONS: tuple[StarterFoodDefinition, ...] = (
    StarterFoodDefinition(
        display_name="Chicken breast",
        aliases=("chicken", "chicken breast", "grilled chicken breast"),
        search_terms=("chicken breast",),
        prefer_terms=("cooked", "roasted", "grilled", "broiled"),
        avoid_terms=("raw", "uncooked", "skin"),
        category="protein",
        notes="Prefer cooked skinless breast entries for everyday logging.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Chicken thigh",
        aliases=("chicken thigh",),
        search_terms=("chicken thigh",),
        prefer_terms=("cooked", "roasted", "grilled", "broiled"),
        avoid_terms=("raw", "uncooked", "skin"),
        category="protein",
        notes="Prefer cooked thigh entries; skip raw-only matches.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Ground chicken",
        aliases=("ground chicken",),
        search_terms=("ground chicken",),
        prefer_terms=("cooked", "prepared"),
        avoid_terms=("raw", "uncooked"),
        category="protein",
        notes="Use cooked/prepared ground chicken only.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Turkey breast",
        aliases=("turkey", "turkey breast"),
        search_terms=("turkey breast",),
        prefer_terms=("cooked", "roasted", "grilled", "broiled"),
        avoid_terms=("raw", "uncooked", "skin"),
        category="protein",
        notes="Prefer cooked turkey breast entries.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Ground turkey",
        aliases=("ground turkey",),
        search_terms=("ground turkey",),
        prefer_terms=("cooked", "prepared"),
        avoid_terms=("raw", "uncooked"),
        category="protein",
        notes="Use cooked/prepared ground turkey only.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Ground beef",
        aliases=("ground beef",),
        search_terms=("ground beef",),
        prefer_terms=("cooked", "prepared"),
        avoid_terms=("raw", "uncooked"),
        category="protein",
        notes="Use cooked/prepared ground beef only.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Beef steak",
        aliases=("steak", "beef steak"),
        search_terms=("beef steak", "steak"),
        prefer_terms=("cooked", "grilled", "broiled", "roasted"),
        avoid_terms=("raw", "uncooked"),
        category="protein",
        notes="Prefer cooked steak entries.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Pork loin",
        aliases=("pork", "pork loin"),
        search_terms=("pork loin", "pork tenderloin"),
        prefer_terms=("cooked", "roasted", "grilled", "broiled"),
        avoid_terms=("raw", "uncooked"),
        category="protein",
        notes="Prefer cooked lean pork entries.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Salmon",
        aliases=("salmon",),
        search_terms=("salmon",),
        prefer_terms=("cooked", "roasted", "grilled", "broiled"),
        avoid_terms=("raw", "uncooked"),
        category="protein",
        notes="Prefer cooked salmon entries.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Tuna",
        aliases=("tuna", "canned tuna"),
        search_terms=("tuna",),
        prefer_terms=("canned", "water", "cooked"),
        avoid_terms=("raw", "uncooked", "oil"),
        category="protein",
        notes="Prefer canned tuna in water or cooked tuna entries.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Shrimp",
        aliases=("shrimp",),
        search_terms=("shrimp",),
        prefer_terms=("cooked", "steamed"),
        avoid_terms=("raw", "uncooked", "breaded"),
        category="protein",
        notes="Prefer cooked plain shrimp entries.",
        raw_source_safe=False,
    ),
    StarterFoodDefinition(
        display_name="Egg",
        aliases=("egg", "eggs", "whole egg"),
        search_terms=("egg",),
        prefer_terms=("whole", "large"),
        avoid_terms=("substitute",),
        category="protein",
        notes="Whole egg is a normal everyday raw-source candidate.",
    ),
    StarterFoodDefinition(
        display_name="Egg white",
        aliases=("egg white", "egg whites"),
        search_terms=("egg white", "egg whites"),
        prefer_terms=("raw", "fresh"),
        avoid_terms=("substitute",),
        category="protein",
        notes="Egg white entries are acceptable as normal source records.",
    ),
    StarterFoodDefinition(
        display_name="Greek yogurt",
        aliases=("greek yogurt", "plain greek yogurt"),
        search_terms=("greek yogurt",),
        prefer_terms=("plain", "nonfat", "lowfat"),
        avoid_terms=("flavored", "vanilla", "strawberry"),
        category="protein",
        notes="Prefer plain Greek yogurt.",
    ),
    StarterFoodDefinition(
        display_name="Cottage cheese",
        aliases=("cottage cheese",),
        search_terms=("cottage cheese",),
        prefer_terms=("lowfat", "low fat", "plain"),
        avoid_terms=("with fruit", "flavored"),
        category="protein",
        notes="Prefer plain cottage cheese.",
    ),
    StarterFoodDefinition(
        display_name="Tofu",
        aliases=("tofu", "firm tofu"),
        search_terms=("tofu",),
        prefer_terms=("firm",),
        avoid_terms=("fried",),
        category="protein",
        notes="Prefer plain tofu entries.",
    ),
    StarterFoodDefinition(
        display_name="Black beans",
        aliases=("black beans", "beans"),
        search_terms=("black beans",),
        prefer_terms=("cooked", "boiled"),
        avoid_terms=("dry", "raw"),
        category="protein",
        notes="Prefer cooked black beans.",
    ),
    StarterFoodDefinition(
        display_name="Pinto beans",
        aliases=("pinto beans",),
        search_terms=("pinto beans",),
        prefer_terms=("cooked", "boiled"),
        avoid_terms=("dry", "raw"),
        category="protein",
        notes="Prefer cooked pinto beans.",
    ),
    StarterFoodDefinition(
        display_name="Lentils",
        aliases=("lentils",),
        search_terms=("lentils",),
        prefer_terms=("cooked", "boiled"),
        avoid_terms=("dry", "raw"),
        category="protein",
        notes="Prefer cooked lentils.",
    ),
    StarterFoodDefinition(
        display_name="Oatmeal",
        aliases=("oatmeal", "cooked oatmeal"),
        search_terms=("oatmeal",),
        prefer_terms=("cooked",),
        avoid_terms=("dry", "instant flavored"),
        category="carbs",
        notes="Prefer cooked oatmeal for ordinary logging.",
    ),
    StarterFoodDefinition(
        display_name="Rice",
        aliases=("rice", "white rice"),
        search_terms=("rice", "white rice"),
        prefer_terms=("cooked", "white"),
        avoid_terms=("dry", "raw", "brown"),
        category="carbs",
        notes="Prefer cooked white rice for the generic rice entry.",
    ),
    StarterFoodDefinition(
        display_name="Brown rice",
        aliases=("brown rice",),
        search_terms=("brown rice",),
        prefer_terms=("cooked",),
        avoid_terms=("dry", "raw"),
        category="carbs",
        notes="Prefer cooked brown rice.",
    ),
    StarterFoodDefinition(
        display_name="Potato",
        aliases=("potato", "potatoes"),
        search_terms=("potato",),
        prefer_terms=("baked", "cooked", "boiled"),
        avoid_terms=("chips", "fried"),
        category="carbs",
        notes="Prefer plain cooked potato entries.",
    ),
    StarterFoodDefinition(
        display_name="Sweet potato",
        aliases=("sweet potato", "sweet potatoes"),
        search_terms=("sweet potato",),
        prefer_terms=("baked", "cooked", "boiled"),
        avoid_terms=("chips", "fried"),
        category="carbs",
        notes="Prefer plain cooked sweet potato entries.",
    ),
    StarterFoodDefinition(
        display_name="Whole wheat bread",
        aliases=("whole wheat bread", "wheat bread"),
        search_terms=("whole wheat bread",),
        prefer_terms=("whole wheat",),
        avoid_terms=("sweet", "raisin"),
        category="carbs",
        notes="Prefer plain whole wheat bread.",
    ),
    StarterFoodDefinition(
        display_name="White bread",
        aliases=("white bread",),
        search_terms=("white bread",),
        prefer_terms=("plain",),
        avoid_terms=("sweet", "raisin"),
        category="carbs",
        notes="Prefer plain white bread.",
    ),
    StarterFoodDefinition(
        display_name="Pasta",
        aliases=("pasta", "noodles"),
        search_terms=("pasta",),
        prefer_terms=("cooked",),
        avoid_terms=("dry", "raw"),
        category="carbs",
        notes="Prefer cooked plain pasta.",
    ),
    StarterFoodDefinition(
        display_name="Tortilla",
        aliases=("tortilla", "flour tortilla"),
        search_terms=("tortilla",),
        prefer_terms=("flour",),
        avoid_terms=("chips", "fried"),
        category="carbs",
        notes="Prefer plain tortilla entries.",
    ),
    StarterFoodDefinition(
        display_name="Bagel",
        aliases=("bagel", "plain bagel"),
        search_terms=("bagel",),
        prefer_terms=("plain",),
        avoid_terms=("sweet", "cinnamon", "raisin"),
        category="carbs",
        notes="Prefer plain bagel entries.",
    ),
    StarterFoodDefinition(
        display_name="Cereal",
        aliases=("cereal",),
        search_terms=("cereal",),
        prefer_terms=("ready to eat",),
        avoid_terms=("sweetened", "chocolate"),
        category="carbs",
        notes="Use only high-confidence plain cereal matches.",
    ),
    StarterFoodDefinition(
        display_name="Quinoa",
        aliases=("quinoa",),
        search_terms=("quinoa",),
        prefer_terms=("cooked",),
        avoid_terms=("dry", "raw"),
        category="carbs",
        notes="Prefer cooked quinoa.",
    ),
    StarterFoodDefinition(
        display_name="Banana",
        aliases=("banana", "bananas"),
        search_terms=("banana",),
        prefer_terms=("raw",),
        avoid_terms=("chips", "dried"),
        category="fruits",
        notes="Raw produce is normal for bananas.",
    ),
    StarterFoodDefinition(
        display_name="Apple",
        aliases=("apple", "apples"),
        search_terms=("apple",),
        prefer_terms=("raw",),
        avoid_terms=("dried", "juice", "sauce"),
        category="fruits",
        notes="Raw produce is normal for apples.",
    ),
    StarterFoodDefinition(
        display_name="Orange",
        aliases=("orange", "oranges"),
        search_terms=("orange",),
        prefer_terms=("raw",),
        avoid_terms=("juice",),
        category="fruits",
        notes="Raw produce is normal for oranges.",
    ),
    StarterFoodDefinition(
        display_name="Grapes",
        aliases=("grapes",),
        search_terms=("grapes",),
        prefer_terms=("raw",),
        avoid_terms=("raisins", "dried"),
        category="fruits",
        notes="Raw produce is normal for grapes.",
    ),
    StarterFoodDefinition(
        display_name="Strawberries",
        aliases=("strawberries", "strawberry"),
        search_terms=("strawberries",),
        prefer_terms=("raw",),
        avoid_terms=("dried", "sweetened"),
        category="fruits",
        notes="Raw produce is normal for strawberries.",
    ),
    StarterFoodDefinition(
        display_name="Blueberries",
        aliases=("blueberries", "blueberry"),
        search_terms=("blueberries",),
        prefer_terms=("raw",),
        avoid_terms=("dried", "sweetened"),
        category="fruits",
        notes="Raw produce is normal for blueberries.",
    ),
    StarterFoodDefinition(
        display_name="Kiwi",
        aliases=("kiwi", "kiwifruit"),
        search_terms=("kiwi", "kiwifruit"),
        prefer_terms=("raw",),
        avoid_terms=("dried",),
        category="fruits",
        notes="Raw produce is normal for kiwi.",
    ),
    StarterFoodDefinition(
        display_name="Pineapple",
        aliases=("pineapple",),
        search_terms=("pineapple",),
        prefer_terms=("raw",),
        avoid_terms=("dried", "syrup", "juice"),
        category="fruits",
        notes="Prefer raw or plain pineapple.",
    ),
    StarterFoodDefinition(
        display_name="Watermelon",
        aliases=("watermelon",),
        search_terms=("watermelon",),
        prefer_terms=("raw",),
        avoid_terms=("juice",),
        category="fruits",
        notes="Raw produce is normal for watermelon.",
    ),
    StarterFoodDefinition(
        display_name="Avocado",
        aliases=("avocado",),
        search_terms=("avocado",),
        prefer_terms=("raw",),
        avoid_terms=("dip", "guacamole"),
        category="fruits",
        notes="Prefer plain avocado entries.",
    ),
    StarterFoodDefinition(
        display_name="Broccoli",
        aliases=("broccoli",),
        search_terms=("broccoli",),
        prefer_terms=("cooked", "boiled", "steamed"),
        avoid_terms=("with cheese", "sauce"),
        category="vegetables",
        notes="Prefer plain broccoli entries.",
    ),
    StarterFoodDefinition(
        display_name="Green beans",
        aliases=("green beans",),
        search_terms=("green beans",),
        prefer_terms=("cooked", "boiled", "steamed"),
        avoid_terms=("with sauce", "casserole"),
        category="vegetables",
        notes="Prefer plain green beans.",
    ),
    StarterFoodDefinition(
        display_name="Spinach",
        aliases=("spinach",),
        search_terms=("spinach",),
        prefer_terms=("raw", "cooked"),
        avoid_terms=("creamed", "sauce"),
        category="vegetables",
        notes="Raw or plain cooked spinach can be everyday entries.",
    ),
    StarterFoodDefinition(
        display_name="Lettuce",
        aliases=("lettuce",),
        search_terms=("lettuce",),
        prefer_terms=("raw",),
        avoid_terms=("dressing",),
        category="vegetables",
        notes="Raw lettuce is normal.",
    ),
    StarterFoodDefinition(
        display_name="Tomato",
        aliases=("tomato", "tomatoes"),
        search_terms=("tomato",),
        prefer_terms=("raw",),
        avoid_terms=("sauce", "juice"),
        category="vegetables",
        notes="Raw tomato is normal.",
    ),
    StarterFoodDefinition(
        display_name="Grape tomatoes",
        aliases=("grape tomatoes", "grape tomato"),
        search_terms=("grape tomatoes", "tomatoes grape"),
        prefer_terms=("raw",),
        avoid_terms=("sauce", "juice"),
        category="vegetables",
        notes="Raw grape tomatoes are normal.",
    ),
    StarterFoodDefinition(
        display_name="Carrot",
        aliases=("carrot", "carrots"),
        search_terms=("carrot",),
        prefer_terms=("raw",),
        avoid_terms=("juice", "cake"),
        category="vegetables",
        notes="Raw carrot is normal.",
    ),
    StarterFoodDefinition(
        display_name="Onion",
        aliases=("onion", "onions"),
        search_terms=("onion",),
        prefer_terms=("raw",),
        avoid_terms=("rings", "fried"),
        category="vegetables",
        notes="Plain onion entries are acceptable.",
    ),
    StarterFoodDefinition(
        display_name="Bell pepper",
        aliases=("bell pepper", "pepper"),
        search_terms=("bell pepper",),
        prefer_terms=("raw",),
        avoid_terms=("stuffed",),
        category="vegetables",
        notes="Raw bell pepper is normal.",
    ),
    StarterFoodDefinition(
        display_name="Cucumber",
        aliases=("cucumber",),
        search_terms=("cucumber",),
        prefer_terms=("raw",),
        avoid_terms=("pickle",),
        category="vegetables",
        notes="Raw cucumber is normal.",
    ),
    StarterFoodDefinition(
        display_name="Zucchini",
        aliases=("zucchini",),
        search_terms=("zucchini",),
        prefer_terms=("raw", "cooked"),
        avoid_terms=("bread", "fried"),
        category="vegetables",
        notes="Plain zucchini entries are acceptable.",
    ),
    StarterFoodDefinition(
        display_name="Mushroom",
        aliases=("mushroom", "mushrooms"),
        search_terms=("mushroom",),
        prefer_terms=("raw", "cooked"),
        avoid_terms=("soup", "sauce"),
        category="vegetables",
        notes="Plain mushroom entries are acceptable.",
    ),
    StarterFoodDefinition(
        display_name="Corn",
        aliases=("corn",),
        search_terms=("corn",),
        prefer_terms=("cooked", "sweet"),
        avoid_terms=("chips", "flour", "syrup"),
        category="vegetables",
        notes="Prefer plain cooked corn.",
    ),
    StarterFoodDefinition(
        display_name="Peas",
        aliases=("peas",),
        search_terms=("peas",),
        prefer_terms=("cooked", "green"),
        avoid_terms=("soup",),
        category="vegetables",
        notes="Prefer plain cooked peas.",
    ),
    StarterFoodDefinition(
        display_name="2% milk",
        aliases=("2% milk", "two percent milk", "reduced fat milk"),
        search_terms=("2% milk", "reduced fat milk"),
        prefer_terms=("2%", "reduced fat"),
        avoid_terms=("chocolate", "flavored"),
        category="dairy_fats_extras",
        notes="Prefer plain reduced-fat milk.",
    ),
    StarterFoodDefinition(
        display_name="Whole milk",
        aliases=("whole milk",),
        search_terms=("whole milk",),
        prefer_terms=("whole",),
        avoid_terms=("chocolate", "flavored"),
        category="dairy_fats_extras",
        notes="Prefer plain whole milk.",
    ),
    StarterFoodDefinition(
        display_name="Skim milk",
        aliases=("skim milk", "nonfat milk"),
        search_terms=("skim milk", "nonfat milk"),
        prefer_terms=("skim", "nonfat"),
        avoid_terms=("chocolate", "flavored"),
        category="dairy_fats_extras",
        notes="Prefer plain skim milk.",
    ),
    StarterFoodDefinition(
        display_name="Cheddar cheese",
        aliases=("cheddar", "cheddar cheese"),
        search_terms=("cheddar cheese",),
        prefer_terms=("cheddar",),
        avoid_terms=("sauce", "spread"),
        category="dairy_fats_extras",
        notes="Prefer plain cheddar cheese.",
    ),
    StarterFoodDefinition(
        display_name="Mozzarella",
        aliases=("mozzarella", "mozzarella cheese"),
        search_terms=("mozzarella",),
        prefer_terms=("part skim", "whole milk"),
        avoid_terms=("sticks", "fried"),
        category="dairy_fats_extras",
        notes="Prefer plain mozzarella.",
    ),
    StarterFoodDefinition(
        display_name="Butter",
        aliases=("butter",),
        search_terms=("butter",),
        prefer_terms=("salted", "unsalted"),
        avoid_terms=("spread", "margarine"),
        category="dairy_fats_extras",
        notes="Prefer plain butter.",
    ),
    StarterFoodDefinition(
        display_name="Olive oil",
        aliases=("olive oil",),
        search_terms=("olive oil",),
        prefer_terms=("olive"),
        avoid_terms=("dressing",),
        category="dairy_fats_extras",
        notes="Prefer plain olive oil.",
    ),
    StarterFoodDefinition(
        display_name="Peanut butter",
        aliases=("peanut butter",),
        search_terms=("peanut butter",),
        prefer_terms=("smooth", "plain"),
        avoid_terms=("reduced fat", "with jelly"),
        category="dairy_fats_extras",
        notes="Prefer plain peanut butter.",
    ),
    StarterFoodDefinition(
        display_name="Almonds",
        aliases=("almonds", "almond"),
        search_terms=("almonds",),
        prefer_terms=("raw", "dry roasted"),
        avoid_terms=("honey", "chocolate"),
        category="dairy_fats_extras",
        notes="Prefer plain almonds.",
    ),
    StarterFoodDefinition(
        display_name="Walnuts",
        aliases=("walnuts", "walnut"),
        search_terms=("walnuts",),
        prefer_terms=("raw",),
        avoid_terms=("candied", "chocolate"),
        category="dairy_fats_extras",
        notes="Prefer plain walnuts.",
    ),
    StarterFoodDefinition(
        display_name="Hummus",
        aliases=("hummus", "commercial hummus"),
        search_terms=("hummus",),
        prefer_terms=("commercial",),
        avoid_terms=("dessert",),
        category="dairy_fats_extras",
        notes="Prefer plain commercial hummus source rows.",
    ),
    StarterFoodDefinition(
        display_name="Salsa",
        aliases=("salsa",),
        search_terms=("salsa",),
        prefer_terms=("ready to serve",),
        avoid_terms=("cheese", "con queso"),
        category="dairy_fats_extras",
        notes="Prefer plain salsa.",
    ),
)


STARTER_FOOD_CATEGORIES: tuple[str, ...] = tuple(
    dict.fromkeys(definition.category for definition in STARTER_FOOD_DEFINITIONS)
)
